baseURL = 'https://example.org/'
languageCode = 'pt-br'
theme = 'Kiera'
title = 'LLM IBM Blog'
author = 'José Gama'
pagination.pagerSize = 10
copyright = "IBM and UFCG - 2025"

[params]
  disableDarkModeCSS = false
  customCSS = ["css/custom.css"]  # Caminho para o arquivo CSS
  [params.assets]
    favicon = 'favicon.ico'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    appletouchicon = 'apple-touch-icon.png'

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3