baseURL = 'https://example.org/'
languageCode = 'pt-br'
theme = 'Kiera'
title = 'LLM IBM Blog'
author = 'José Gama'
pagination.pagerSize = 10
copyright = "IBM & UFCG - 2025"

[params]
  disableDarkModeCSS = true
  customCSS = ["css/custom.css"]  # Caminho para o arquivo CSS
  [params.assets]
    favicon = 'favicon.ico'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    appletouchicon = 'apple-touch-icon.png'

[menu]
  [[menu.main]]
    name = "Equipe"
    url = "/team/"
    weight = 3

date = ["publishDate"]
ignoreErrors = ["error-disable-date"]
hideMeta = true