baseURL = 'https://example.org/'
languageCode = 'pt-br'
theme = 'Kiera'
title = 'LLM IBM UFCG'
pagination.pagerSize = 10
copyright = "IBM & UFCG - 2025"

[params]
  tagline = "Blog com relatórios periódicos das tarefas realizadas."
  disableDarkModeCSS = true
  customCSS = ["css/custom.css", "css/font.css"]  # Caminho para o arquivo CSS
  [params.assets]
    favicon = 'favicon.ico'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    appletouchicon = 'apple-touch-icon.png'

[menu]
  [[menu.main]]
    name = "Equipe"
    url = "/team/"
    weight = 3
