baseURL = 'https://example.org/'
languageCode = 'pt-br'
theme = 'PaperMod'
title = 'LLM IBM Blog'
author = 'José Gama'
pagination.pagerSize = 10
copyright = "IBM and UFCG - 2025"

[params]
  [params.head]
    logo = 'logo.png'
  [params.assets]
    favicon = 'favicon.ico'
    favicon16x16 = 'favicon-16x16.png'
    favicon32x32 = 'favicon-32x32.png'
    appletouchicon = 'apple-touch-icon.png'
    
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3