name: Deploy Hugo to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você quer fazer deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Hugo via Docker
        run: docker run --rm -v ${{ github.workspace }}:/site klakegg/hugo:latest

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public